#page title
page_title: Atlas - Injection Tracker # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: # Enter Google Play Store URL.
presskit_download_link:
    # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: assets/appicon.png # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: Atlas - Injection Tracker # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: Free (Closed Beta) # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: A mobile application for UCSF that allows researchers to track outcomes of spinal injections longitudinally.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: Timothy Park
your_link: https://tmprk.github.io
your_city: San Francisco, CA
email_address: ucsf.atlasapp@gmail.com
facebook_username:
instagram_username:
twitter_username:
github_username:
youtube_username:

# Feature List; Edit, add or remove features to be presented.
features:
    - title: Local and Remote Notifications
      description: Receive notifications whenever your surveys are due. No internet connection required.
      fontawesome_icon_name: magic

    - title: Reschedule surveys
      description: Either take the surveys at the intended time or 5-10 minutes whenever it is convenient.
      fontawesome_icon_name: clipboard-list

    - title: Chat with your researcher
      description: Realtime chat that enables you to speak with your researcher about any issues.
      fontawesome_icon_name: comment

    - title: Clean progress tracker
      description: View pain scores graphed over time in a simple and clean visual.
      fontawesome_icon_name: chart-bar

    - title: Keep local data even when logged out
      description: Pain scores remain on device unless the app is deleted.
      fontawesome_icon_name: arrow-alt-circle-down

    - title: Browse overviews of your submissions
      description: View responses to previous results in a user-friendly interface even when offline.
      fontawesome_icon_name: search

    - title: Suggestion Box
      description: Experiencing a persisting issue? Want to suggest a feature? Open an issue in the feedback box (located in settings).
      fontawesome_icon_name: exclamation

    - title: Built with native Swift UIKit
      description: Written in 100% Swift and is built to support both iPhone and iPad.
      fontawesome_icon_name: mobile

    - title: Frequent updates and improvement
      description: We are working to make the app better every iteration, however, do expect bugs in the closed beta.
      fontawesome_icon_name: sync

    - title: # New Feature Title
      description: # New Feature Description
      fontawesome_icon_name: # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.jpg # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: black # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
    style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
    - LICENSE
    - README.md
    - CNAME

collections:
    pages:
        output: true
        permalink: /:path/

# Markdown rendering
markdown: kramdown
